Feature/cod 31
Vladimir9812/middle.game.praktikum.yandex pull request #11
Opened 2023-09-20 08:38 UTC by nikitandro

2023-09-20 12:38 UTC, kipish0293 approved these changes
У меня нет критичных замечаний.

2023-09-20 12:38 UTC, kipish0293 commented on packages/client/src/engine/utils/animate.ts
> +export default function animate({ update, render }: AnimateInputParameters) {
Эта функция на будущее ?

2023-09-20 12:38 UTC, kipish0293 commented on packages/client/src/engine/core/Game/Game.ts
> +  public start(): void {
Код дублируется в animates.ts

2023-09-20 14:00 UTC, brovan-rus commented on packages/client/src/engine/core/Vector/Vector.ts
> +    // const newY = Math.round(this.y * scalar)
Лишние комменты

2023-09-20 14:00 UTC, brovan-rus commented on packages/client/src/engine/core/Vector/Vector.ts
> +    // const newY = Math.round(this.y / scalar)
Комменты

2023-09-20 14:00 UTC, brovan-rus commented on packages/client/src/engine/core/AbstractEntity/AbstractEntity.ts
> +  // public resolveCollision(other: AbstractEntity) {}
Закоменченые методы - если они нужны на будущее лучше писать TODO комменты, чтобы потом понимать, что запланированно сделать в этом месте
https://www.jetbrains.com/help/webstorm/using-todo.html

2023-09-20 14:00 UTC, brovan-rus commented on packages/client/src/engine/core/InputService/types.ts
> +export type KeyInputListener = (value: boolean) => void;
Сюда точно аргументом приходит boolean, а не event type?

2023-09-20 14:00 UTC, brovan-rus commented on packages/client/src/engine/core/InputService/types.ts
> +export type KeyInputEvents = {
Не могу найти в коде, где этот тип используется.

2023-09-20 14:00 UTC, brovan-rus commented on packages/client/src/engine/entities/SampleEntity/SampleEntity.ts
> +
Комменты стоит удалить либо написать TODO, чтобы понять для чего этот код будет дальше использоваться

2023-09-20 14:00 UTC, brovan-rus commented on packages/client/src/engine/entities/SampleEntity/SampleEntity.ts
> +    context.fillStyle = '#000';
Цвет стоит вынести в переменную

2023-09-20 14:00 UTC, brovan-rus commented on packages/client/src/engine/entities/SampleEntity/SampleEntity.ts
> +  // }
Комменты, удалить либо TODO

2023-09-21 16:55 UTC, Olegas commented on packages/client/src/engine/core/EntityService/EntityService.ts
> +    this.entities.splice(0, this.entities.length);
Совет: самый быстрый и эффективный способ очистить массив = this.entities.length = 0

2023-09-21 16:55 UTC, Olegas commented on packages/client/src/engine/core/EntityService/EntityService.ts
> +  private constructor() {
Лайк за правильно реализованный синглтон с закрытым конструктором

2023-09-21 17:04 UTC, Olegas requested changes
Красиво и аккуратно. Мне понравилось.
Есть пара советов и пара замечаний к коду - судя по всему забыл сделать поддержку остановки игры - анимация бесконечная и не убирается подписка на события клавиатуры нигде.
Не понял один момент - где сбрасывается признак что клавиша нажата? Чтение нашел, а сброс не нашел. Не будет ли бесконечно обрабатываться одна нажатая клавиша?

2023-09-21 17:04 UTC, Olegas commented on packages/client/src/engine/core/Game/Game.ts
> +      requestAnimationFrame(gameLoop);
А как закончить эту анимацию? Выглядит так что у класса игры забыли возможность эту игру остановить

2023-09-21 17:04 UTC, Olegas commented on packages/client/src/engine/core/InputService/InputService.ts
> +    });
В этом классе забыто удаление подписки на события при разрушении игры.

2023-09-21 17:04 UTC, Olegas commented on packages/client/src/engine/core/InputService/types.ts
> +}
Нет ли в TS существующего типа под все значения кодов клавиш?

2023-09-21 17:04 UTC, Olegas commented on packages/client/src/engine/entities/SampleEntity/SampleEntity.ts
> +    }
А где сбрасывается состояние нажатия кнопки?

2023-09-22 04:09 UTC, nikitandro commented on packages/client/src/engine/core/InputService/types.ts
> +}
К сожалению нет, сам искал, пришлось самому писать тип

2023-09-22 04:25 UTC, nikitandro commented on packages/client/src/engine/entities/SampleEntity/SampleEntity.ts
> +    }
В этом методе только проверяется, нажата кнопка или нет. Состояние кнопки лежит в InputService и там же и обрабатывается

2023-09-23 13:43 UTC, Olegas approved these changes
Работа принята

2023-09-23 13:46 UTC, merged