Feature/cod 38 Added ErrorBoundary for App and wrapped components
Vladimir9812/middle.game.praktikum.yandex pull request #13
Opened 2023-09-21 08:04 UTC by kipish0293

2023-09-21 12:27 UTC, brovan-rus requested changes

2023-09-21 12:27 UTC, brovan-rus commented on packages/client/src/components/ErrorBoundary/components/ErrorFallbackComponent.tsx
> +          An error occurred while loading the component
Тут и везде дальше. Тексты лучше выносить в переменные.

2023-09-21 12:27 UTC, brovan-rus commented on .eslintrc
> +        "code": 150
Не уверен насчет того, что именно 150 хорошая идея. 
Тут есть рекомендации по максимальной длине по языкам 
https://www.codereadability.com/maximum-line-length/ и обсуждение внизу интересное. Думаю, что 80 маловато, но и 150 довольно много, чтобы читать всё в строчку, особенно с ноута. Думаю, стоит обсудить в группе и выбрать стандарт.
Когда выберем - поменять и .prettierrc и .editorconfig, иначе сейчас есть рассинхрон между конфигами.

2023-09-21 12:50 UTC, kipish0293 commented on packages/client/src/components/ErrorBoundary/components/ErrorFallbackComponent.tsx
> +          An error occurred while loading the component
@brovan-rus не согласен. эти тексты больше нигде не используются.

2023-09-21 12:51 UTC, kipish0293 commented on .eslintrc
> +        "code": 150
100 это для какого-то маленького экрана квадратного))
150 кажется лучшей идеей для меня, предлагаю вынести на голосование

2023-09-21 18:32 UTC, brovan-rus commented on packages/client/src/components/ErrorBoundary/components/ErrorFallbackComponent.tsx
> +          An error occurred while loading the component
Да, но в компоненте тексты лучше выносить в переменную, так их легче менять и поддерживать. Не в отдельный файл, а в начале. Если несколько текстов в компоненте, стоит сделать объект типа componentTexts: {title: '', link: ''}.
Так, например нужно было поменять кнопку с go back на go home и приходилось обращаться к тексту.
Обычно в компонентах тексты напрямую писать - плохая практика.

2023-09-21 20:49 UTC, Vladimir9812 commented on packages/client/src/components/ErrorBoundary/components/ErrorFallbackPage.tsx
> +        <Button onClick={goToHome} mt={5}>
Необязательно создавать функцию goToHome отдельную. Можно и сразу в шаблоне написать onClick={navigate('/')}

2023-09-21 20:49 UTC, Vladimir9812 commented on packages/client/src/pages/register/Register.tsx
>    return (
Хорошей практикой считается перед return ставить пробел сверху

2023-09-22 21:23 UTC, brovan-rus approved these changes

2023-09-23 14:24 UTC, Vladimir9812 approved these changes

2023-09-23 14:27 UTC, merged