Added 503 page
Vladimir9812/middle.game.praktikum.yandex pull request #14
Opened 2023-09-21 08:56 UTC by kipish0293

2023-09-21 12:03 UTC, brovan-rus requested changes

2023-09-21 12:03 UTC, brovan-rus commented on packages/client/src/pages/serviceUnavailable/ServiceUnavailable.tsx
> +            <Link className="service-unavailable__go-back-link" to="/">
Тут должет быть именно переход назад, а не в корень

2023-09-21 12:03 UTC, brovan-rus commented on packages/client/src/pages/serviceUnavailable/ServiceUnavailable.css
> +.service-unavailable__go-back-link {
Как нам говорил ментор, лучше использовать module.css. Плюс в таком  случае можно делать не уникальне названия классов и убрать везде в начале "service-unavailable"

2023-09-21 12:53 UTC, kipish0293 commented on packages/client/src/pages/serviceUnavailable/ServiceUnavailable.tsx
> +            <Link className="service-unavailable__go-back-link" to="/">
@brovan-rus куда назад если человек зашел по ссылке из вне? в корень считаю будет удобней

2023-09-21 13:35 UTC, brovan-rus commented on packages/client/src/pages/serviceUnavailable/ServiceUnavailable.tsx
> +            <Link className="service-unavailable__go-back-link" to="/">
Да, хорошо, поменял на Go home

2023-09-21 20:45 UTC, Vladimir9812 commented on packages/client/src/const/errorLinkText.ts
А мы будем переменные отдельно по файлам хранить? Не лучше ли сделать один общий файл constants и туда все складывать? + необходимо добавить alias под это дело

2023-09-21 20:46 UTC, Vladimir9812 commented on packages/client/src/const/errorLinkText.ts
> +export const errorLinkText = 'Go home';
А мы будем переменные отдельно по файлам хранить? Не лучше ли сделать один общий файл constants и туда все складывать? + необходимо добавить alias под это дело

2023-09-21 21:10 UTC, kipish0293 commented on packages/client/src/const/errorLinkText.ts
> +export const errorLinkText = 'Go home';
@Vladimir9812 это Костя сделал правки в моей ветке, я его попросил. А так, в данном случае я не стал бы выносить эту фразу в переменную потому что она 2 раза в коде встречается. Но в другой ветке я завел глобальный файл textConstance как раз для констант

2023-09-21 21:19 UTC, Vladimir9812 commented on packages/client/src/const/errorLinkText.ts
> +export const errorLinkText = 'Go home';
То есть потом у нас будет отдельный файл для констант и эти изменения уйдут?

2023-09-22 19:33 UTC, kipish0293 commented on packages/client/src/const/errorLinkText.ts
> +export const errorLinkText = 'Go home';
@Vladimir9812  Убрал глобальные константы. Завел переменные локально в файлах. Если решим в дальнейшем создадим один файл глобальное хранилище текстовых переменных

2023-09-22 21:23 UTC, brovan-rus requested changes

2023-09-22 21:23 UTC, brovan-rus commented on packages/client/src/pages/notFound/NotFound.tsx
> +              {GO_GOME_TEMPLATE}
Тут и дальше
GO_HOME_TEMPLATE

2023-09-23 07:07 UTC, kipish0293 commented on packages/client/src/pages/notFound/NotFound.tsx
> +              {GO_GOME_TEMPLATE}
Не понимаю, что значит этот комментарий ?

2023-09-23 14:43 UTC, Vladimir9812 approved these changes

2023-09-23 14:44 UTC, merged