Feature/cod 21 Added a Forum page
Vladimir9812/middle.game.praktikum.yandex pull request #17
Opened 2023-09-23 08:59 UTC by kipish0293

2023-09-23 09:06 UTC, nikitandro commented on packages/client/src/App.tsx
> +          <Route index path="/" element={<MainPage />} />
Здесь index не нужен, он используется во вложенных роутах, когда path у вложенного роута должен быть таким же, как родительский

2023-09-23 09:08 UTC, kipish0293 commented on packages/client/src/App.tsx
> +          <Route index path="/" element={<MainPage />} />
Да ты прав, я забыл обернуть приложение в один роут с path "/"

2023-09-23 09:08 UTC, nikitandro commented on packages/client/src/components/FormTextArea/FormTextArea.module.css
> +  width: 100% !important;
Лучше стараться избегать `!important`

2023-09-23 09:09 UTC, nikitandro commented on packages/client/src/components/Pagination/Pagination.module.css
> +  background-color: #febe60 !important;
Лучше стараться избегать `!important`

2023-09-23 09:09 UTC, nikitandro commented on packages/client/src/components/Pagination/Pagination.module.css
> +    border: 3px solid #e53e3e !important;
Сам знаешь)

2023-09-23 09:09 UTC, kipish0293 commented on packages/client/src/components/FormTextArea/FormTextArea.module.css
> +  width: 100% !important;
Согласен, но в данном случае обосновано тем, что компонент chakra не умеет быть 100%

2023-09-23 09:11 UTC, nikitandro commented on packages/client/src/pages/forum/Forum.module.css
> +  border-radius: 0 0 6px 6px !important;
Сам знаешь)

2023-09-23 09:23 UTC, nikitandro commented on packages/client/src/pages/forum/components/ForumList.tsx
> +  const [itemOffset, setItemOffset] = useState(0);
Параметры сортировки, фильтрации и пагинации лучше хранить в query параметрах
Так можно передавать ссылки с конкретными параметрами. Также после перезагрузки страницы состояние страницы будет сохраняться

2023-09-23 09:34 UTC, nikitandro commented on packages/client/src/components/Pagination/Pagination.tsx
> +  handlePageClick: (e: { selected: number }) => void;
Не очень понимаю, зачем передавать объект с одним параметром?
Возможно там будут ещё параметры, но если нет, то имеет смысл просто прокидывать number

2023-09-23 09:36 UTC, kipish0293 commented on packages/client/src/components/Pagination/Pagination.tsx
> +  handlePageClick: (e: { selected: number }) => void;
Этот объект формирует библиотека.

2023-09-23 09:37 UTC, kipish0293 commented on packages/client/src/pages/forum/components/ForumList.tsx
> +  const [itemOffset, setItemOffset] = useState(0);
Сделаем это в будующем, вместе с бэкендом

2023-09-23 09:40 UTC, nikitandro commented on packages/client/src/pages/forum/components/CreateTopic.tsx
> +      dateOfCreate: new Date().toISOString(),
Лучше назвать либо просто date, либо creationDate, так будет грамматически верно

2023-09-23 09:41 UTC, nikitandro approved these changes
В целом всё хорошо

2023-09-23 09:55 UTC, kipish0293 commented on packages/client/src/App.tsx
> +          <Route index path="/" element={<MainPage />} />
@nikitandro поправил

2023-09-23 09:59 UTC, kipish0293 commented on packages/client/src/components/Pagination/Pagination.module.css
> +  background-color: #febe60 !important;
Тут все же оставлю как есть

2023-09-23 09:59 UTC, kipish0293 commented on packages/client/src/components/Pagination/Pagination.module.css
> +    border: 3px solid #e53e3e !important;
@nikitandro убрал

2023-09-23 09:59 UTC, kipish0293 commented on packages/client/src/pages/forum/Forum.module.css
> +  border-radius: 0 0 6px 6px !important;
@nikitandro Убрал

2023-09-23 10:00 UTC, kipish0293 commented on packages/client/src/pages/forum/components/CreateTopic.tsx
> +      dateOfCreate: new Date().toISOString(),
@nikitandro Переименовал

2023-09-23 14:52 UTC, Olegas requested changes
Добрый день. 
В целом все хорошо, но есть замечания по коду.
Давай их исправим и будет все круто!

2023-09-23 14:52 UTC, Olegas commented on packages/client/src/components/FormInput/FormInput.tsx
> +    onChange = (e) => console.log(e.target),
Вот эта конструкция выглядит явно отладочной. Лучше не оставлять такое в реальном коде приложения.

2023-09-23 14:52 UTC, Olegas commented on packages/client/src/components/FormTextArea/FormTextArea.tsx
> +  console.log(value);
Еще один отладочный вывод, нужно убрать.

2023-09-23 14:52 UTC, Olegas commented on packages/client/src/pages/forum/components/CreateTopic.tsx
> +  onConfirm: (data: any) => void;
Вот здесь, судя по коду далее, тип точно понятен. Его бы сразу тут нормальный написать, вместо any

2023-09-23 14:52 UTC, Olegas commented on packages/client/src/pages/forum/components/CreateTopic.tsx
> +    if (element.name === 'topit-name') {
Опечатка в слове topic

2023-09-23 14:52 UTC, Olegas commented on packages/client/src/pages/forum/components/ForumTopic.tsx
> +    fetchData();
Очень сложно. Зачем тут асинхронная функция? В ней нет ни одного await. Зачем новый Promise - он даже никуда не возвращается. А раз вы запустили setTimeout - нужно в "разрушении" эффекта не забыть таймер остановить.

2023-09-23 14:52 UTC, Olegas commented on packages/client/src/pages/forum/components/ForumTopic.tsx
> +  const handlePageClick = (event: { selected: number }) => {
Некоторые функции не завернуты в useCallback, хотя было бы полезно.

2023-09-24 08:44 UTC, Olegas approved these changes
Отлично! Работа принята, спасибо.

2023-09-24 09:33 UTC, merged