Feature/cod 14 Added main/game over pages
Vladimir9812/middle.game.praktikum.yandex pull request #21
Opened 2023-09-25 22:02 UTC by Vladimir9812

Были добавлены 2 новых экрана:

- Главная страница
- Страница завершения игры

2023-09-25 22:07 UTC, Vladimir9812 commented
Уважаемый ревьюер, эта задачка не была самой объемной в 5 спринте. Самой объемной была задача по базовой настройке структуры проекта и добавление react-router-dom. Я сразу замержил ее, тк она тормозила начало разработки.
 
Вы можете посмотреть на нее по ссылке ниже:
https://github.com/Vladimir9812/middle.game.praktikum.yandex/pull/1

2023-09-26 13:05 UTC, IvanPeleshok commented on packages/client/src/pages/gameOver/GameOver.tsx
> +const enum GameOverText {
Предлагаю вынести в отдельный модуль
Замечательно, что знаете про существование const enum

2023-09-26 13:06 UTC, IvanPeleshok commented on packages/client/src/pages/gameOver/GameOver.tsx
> +            {GameOverText.gameOver.toUpperCase()}
Нет никакой необходимости приводить к заглавным (не вижу необходимости)
Предлагаю изначально объявить заглавными текст, т.к больше нигде не используется

2023-09-26 13:07 UTC, IvanPeleshok commented on packages/client/src/pages/main/Main.tsx
> +const enum MainText {
Аналогично про то, что лучше вынести в отдельный модуль и регистр букв

2023-09-26 13:09 UTC, IvanPeleshok requested changes
Замечательная работа, всё нравится :)

Есть небольшая просьба, т.к вам в дальнейшем будет самим удобнее, когда структура предсказуема

2023-09-27 05:31 UTC, kipish0293 approved these changes

2023-09-28 09:26 UTC, brovan-rus approved these changes

2023-09-28 09:26 UTC, brovan-rus commented on packages/client/src/pages/main/Main.module.css
> +  &-button {
У меня и ,как я понимаю, у других ребят не используется БЭМ в наименовании стилей

2023-09-28 09:26 UTC, brovan-rus commented on packages/client/src/pages/main/Main.tsx
> +              className={styles['nav-button__link']}
Лучше через точку

2023-09-28 13:04 UTC, IvanPeleshok approved these changes
Всё замечательно!
Апрув :)

2023-09-28 16:23 UTC, merged