Feature/cod 54 Tests
Vladimir9812/middle.game.praktikum.yandex pull request #25
Opened 2023-10-06 18:02 UTC by Valeria2312

2023-10-06 19:19 UTC, brovan-rus requested changes

2023-10-06 19:19 UTC, brovan-rus commented on packages/client/src/components/Modal/Modal.test.tsx
> +  expect(screen.getByTestId('modal-body')).toBeInTheDocument();
Тут и везде. Для атомарности тестов - один expect  на один тест, в теории об этом было

2023-10-06 19:19 UTC, brovan-rus commented on packages/client/src/components/Modal/Modal.tsx
> +        <ModalCloseButton data-testid="modal-close-btn" />
Тут и везде, консистентное наименование data-test-id

2023-10-06 19:19 UTC, brovan-rus commented on packages/client/src/engine/core/AbstractEntity/AbstractEntity.test.ts
> +  it('should create an instance of AbstractEntity', () => {
Тут и везде, названия тестов с лучше с глагола "creates an instance of AbstractEntity"

2023-10-06 19:19 UTC, brovan-rus commented on packages/client/src/engine/core/Game/Game.test.ts
> +    animationFrameMock.mockRestore();
Обнулить переменную Game для наглядности

2023-10-06 19:19 UTC, brovan-rus commented on packages/client/src/engine/core/InputService/InputService.test.ts
> +    expect(inputService.getInputKeyState(keyCode)).toBe(true);
Один expect  на тест

2023-10-06 19:19 UTC, brovan-rus commented on packages/client/vite.config.ts
> -  // },
Комменты

2023-10-06 19:19 UTC, brovan-rus commented on packages/client/src/engine/core/Game/Game.test.ts
> +    expect(renderCalled).toBe(true);
Тут и везде, нужно разделять строкой части теста - установку, действие и проверку.

2023-10-07 09:08 UTC, Valeria2312 commented on packages/client/src/components/Modal/Modal.tsx
> +        <ModalCloseButton data-testid="modal-close-btn" />
Судя по всему jest-dom работает именно с таким написанием. https://github.com/testing-library/jest-dom

2023-10-07 09:34 UTC, nikitandro approved these changes

2023-10-07 16:24 UTC, brovan-rus approved these changes

2023-10-07 16:24 UTC, brovan-rus commented on packages/client/src/components/Modal/Modal.test.tsx
> +  const { getByTestId } = render(
Можно рендерить каждый раз компонент в переменную wrapper (можно делать в beforeEach, но для наглядности лучше тут.

2023-10-07 16:24 UTC, brovan-rus commented on packages/client/src/components/Modal/Modal.test.tsx
> +    <Modal onClose={onClose} isOpen size="lg" body={body} title={title} />,
Одинаковый код Modal - в переменную вне теста, а лучше в фукцию createModal

2023-10-07 16:24 UTC, brovan-rus commented on packages/client/src/engine/core/Game/Game.test.ts
> +    game = new Game(document.createElement('canvas'), MockScene);
Так хорошо, но можно для наглядности в каждом из тестов создавать переменную Game. В случае тестов избыточность кода не так страшна.

2023-10-07 16:24 UTC, brovan-rus commented on packages/client/src/components/Modal/Modal.tsx
> +        <ModalCloseButton data-testid="modal-close-btn" />
Ок

2023-10-07 20:21 UTC, IvanPeleshok approved these changes
Проделана огромная работа!
Отлично постарались!

Комментарии от ваших сокомандников имеют смысл, классно, что есть опытные ребята в команде! Предлагаю взять рекомендации на вооружение

Критических моментов не нашёл

Поздравляю, работа принята!

2023-10-10 19:21 UTC, merged