Feature/cod 59 Add api for leaderboard
Vladimir9812/middle.game.praktikum.yandex pull request #34
Opened 2023-10-28 16:21 UTC by Valeria2312

2023-10-29 10:32 UTC, brovan-rus requested changes

2023-10-29 10:32 UTC, brovan-rus commented on packages/client/src/pages/game/Game.tsx
> +      teamName: user?.login,
teamName может быть undefined?

2023-10-29 10:32 UTC, brovan-rus commented on packages/client/src/pages/leaderboard/Leaderboard.tsx
> +          {leaderboard?.map((item: any, index: number) => (
лучше не использовать any, а явно типизировать leaderboard

2023-10-29 10:32 UTC, brovan-rus commented on packages/client/src/utils/createLeaderboard.ts
> +  return array.map((item: any, index: number) => ({
any

2023-10-29 11:38 UTC, Valeria2312 commented on packages/client/src/pages/game/Game.tsx
> +      teamName: user?.login,
У нас user может быть undefined в стейте.

2023-10-29 16:41 UTC, brovan-rus commented on packages/client/src/pages/game/Game.tsx
> +      teamName: user?.login,
Да, но тогда мы в принципе не можем открыть не защищенные роуты.

2023-10-29 16:41 UTC, brovan-rus approved these changes

2023-10-29 18:47 UTC, kipish0293 approved these changes
В целом все хорошо, оставил пару комментариев-вопросов(хотелось бы получить на них ответ)

а так апрув.👍

2023-10-29 18:47 UTC, kipish0293 commented on packages/client/src/pages/game/Game.tsx
> +      teamName: user?.login,
@Valeria2312 onStopClick  не может быть вызван в теории неавторизованным пользователем, но лишняя защита по-моему не помешает как у тебя)

2023-10-29 18:47 UTC, kipish0293 commented on packages/client/src/store/slices/ScoreSlice/ScoreSlice.ts
> +  error: '',
@Valeria2312 пока не спустился вниз, где ты присваиваешь error = action.error.message, я думал что error это экземпляр Error, мне кажется название переменной было бы понятней например errorMessage или наоборот в error сохранять весь ответ ошибки и тогда можно было бы оставить error

2023-10-29 18:47 UTC, kipish0293 commented on packages/client/src/utils/createLeaderboard.ts
> +  array.splice(0, 1);
@Valeria2312 а для чего тут сплайсить массив с данными?  что там на первой строчке?

2023-10-29 19:10 UTC, Valeria2312 commented on packages/client/src/store/slices/ScoreSlice/ScoreSlice.ts
> +  error: '',
Согласна, делала ежинообразно с остальным slice, тогда везде поменяю на errorMessage.

2023-10-29 19:12 UTC, Valeria2312 commented on packages/client/src/utils/createLeaderboard.ts
> +  array.splice(0, 1);
Первым приходит объект который я отправляю в запросе на получение лидерборда, а после уже непосредственно лидерборда.

2023-10-30 21:17 UTC, Olegas commented on packages/client/src/pages/game/Game.tsx
> +      teamName: user?.login,
А разве teamName не должен быть константой для вашего проекта целиком?

2023-10-30 21:18 UTC, Olegas requested changes
Добрый день.
Есть вопрос по использованию API лидерборда - почему-то у вас поле teamName меняется с каждым запросом, хотя, кажется, должно быть одной константой на весь ваш проект.

2023-11-01 15:23 UTC, Olegas approved these changes
Работа принята

2023-11-01 17:57 UTC, merged