COD-57 Added redux support for SSR
Vladimir9812/middle.game.praktikum.yandex pull request #37
Opened 2023-11-06 10:18 UTC by nikitandro

2023-11-06 17:51 UTC, Valeria2312 approved these changes

2023-11-06 19:23 UTC, IvanPeleshok requested changes
Проделана большая работа!
Хорошо потрудились

Есть некоторые замечания, предлагаю доработать

Хорошего дня :)

2023-11-06 19:23 UTC, IvanPeleshok commented on packages/client/src/store/slices/UserSlice.ts
> +// const initialState: UserState = {
Если не используется, предлагаю удалить (YAGNI - https://web-creator.ru/articles/yagni)

2023-11-06 19:23 UTC, IvanPeleshok commented on packages/server/index.ts
> +      const preloadedUser = `<script>window.__USER_STATE__=${initialUserState}</script>`;
А если нужны будут данные не только для модуля user?
Предлагаю посмотреть в сторону `preloadedstate` для `configureStore ` https://redux-toolkit.js.org/api/configureStore#preloadedstate

2023-11-06 19:23 UTC, IvanPeleshok commented on packages/client/src/store/slices/UserSlice.ts
> +  preloadedState = window.__USER_STATE__;
После установки данных предлагаю удалять их из объекта window (`delete window.__USER_STATE__`)

2023-11-06 19:23 UTC, IvanPeleshok commented on packages/server/index.ts
> +const initialUserState = JSON.stringify({
Предлагаю вынести в модуль, а лучше на стороне сервера запрашивать данные, чтобы не отдавать мок данных

2023-11-07 09:37 UTC, nikitandro commented on packages/server/index.ts
> +const initialUserState = JSON.stringify({
Я не очень понимаю, как на сервере узнать, какие данные запросить, чтобы отправить их на клиент

2023-11-07 19:44 UTC, IvanPeleshok approved these changes
Качественная работа!

Есть небольшое предложение по доработке

Критических замечаний не обнаружено!

Поздравляю, работа принята!

Хорошего дня :)

2023-11-07 19:44 UTC, IvanPeleshok commented on packages/server/preloadState.ts
> +export default async function preloadState() {
Супер, что вынесли в отдельный модуль

Есть предложения: 
1. Экспортировать функцию без default
2. Вынести получение user в отдельный метод, чтобы было удобнее масштабировать и тестировать (и т.д)
3. Не забывать, что есть и другие поля в модуле (возможно затерялось поле isLoading)

2023-11-09 08:16 UTC, merged