Cod 65
Vladimir9812/middle.game.praktikum.yandex pull request #41
Opened 2023-11-13 23:41 UTC by brovan-rus

### Какую задачу решаем
Создано API форума на сервере, описание в Readme, добавлена валидация, разбиты docker-compose.dev и docker-compose.prod, поправлен preload стейта юзера
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-11-14 06:50 UTC, Olegas requested changes
Добрый день.
В реализации есть ошибки. Написал подробные комментарии где и что нужно исправить.
Требуется доработка.

2023-11-14 06:50 UTC, Olegas commented on Dockerfile.dev
> +CMD cd /app/packages/server && yarn dev
Тут что-то не так. Содержимое повторяется два раза почти одинаковое. Зачем так?

2023-11-14 06:50 UTC, Olegas commented on packages/server/controllers/answer.ts
> +  const { author, text, thread } = request.body;
Есть ли у вас мидлвара, которая проверяет права? Если уже есть то данные об авторе нужно брать из нее, а не из тела запроса. Иначе можно будет создавать сущности для произвольного пользователя просто указав его данные в запросе руками.

2023-11-14 06:50 UTC, Olegas commented on packages/server/controllers/answer.ts
> +  Answer.destroy({ where: { id: answerId } })
Здесь нужна проверка на то что текущий пользователь - хозяин удаляемой сущности

2023-11-14 06:50 UTC, Olegas commented on packages/server/controllers/answer.ts
> +  Answer.update({ title, text }, { where: { id: answerId } })
Здесь нужна проверка на то что текущий пользователь - хозяин изменяемой сущности

2023-11-14 06:50 UTC, Olegas commented on packages/server/controllers/comment.ts
> +import { Comment, IComment } from '../models/Comment';
Здесь все те же замечания по проверке автора

2023-11-14 06:50 UTC, Olegas commented on packages/server/controllers/thread.ts
> +import { Thread } from '../models/Thread';
Здесь аналогичные проблемы с проверкой прав

2023-11-14 06:50 UTC, Olegas commented on packages/server/index.ts
>        const preloadedStateHtml = `<script>window.__PRELOADED_STATE__=${JSON.stringify(
Здесь у вас XSS-инъекция, данные стейта не заэкранированы. Нужно заэкранировать

2023-11-14 06:50 UTC, Olegas commented on packages/server/middlewares/auth.ts
> +  request.user = user;
Вот эти данные нужно использовать внутри API форума для проверки прав и выяснения кто автор

2023-11-14 06:50 UTC, Olegas commented on packages/server/models/Answer.ts
> +  thread: {
Т.к. вы ищете ответы по ид треда, должен быть описан соответствующий индекс.

2023-11-14 06:50 UTC, Olegas commented on packages/server/models/Comment.ts
> +  answer: {
Здесь тоже не хватает индекса для поиска комментариев от ответа

2023-11-15 15:27 UTC, Olegas requested changes
В реализации есть ошибки, во всех контроллерах одинаковые. Написал комментарии в контроллере answer, в остальных контроллерах все те же самые проблемы - не стал множить комментарии, но в них нужно исправить аналогично.

2023-11-15 15:27 UTC, Olegas commented on packages/server/controllers/answer.ts
> +  const answerToDelete = await Answer.findOne({ where: { author: userId } });
Вот тут не понял что происходит. Почему мы ищем один ответ по данному ид пользователя? Разве не надо искать его по ид ответа из запроса (answerId)?

2023-11-15 15:27 UTC, Olegas commented on packages/server/controllers/answer.ts
> +  if (answerToDelete?.id.toString() === answerId) {
...И вот эта проверка тогда не понадобится

2023-11-15 15:27 UTC, Olegas commented on packages/server/controllers/answer.ts
> +  const answerToDelete = await Answer.findOne({ where: { author: userId } });
Почему "to delete"? Мы же здесь редактируем, а не удаляем. Копипаста из метода удаления?

2023-11-16 06:27 UTC, Olegas approved these changes
Работа принята, спасибо, все хорошо!

2023-11-16 12:10 UTC, nikitandro approved these changes

2023-11-16 12:10 UTC, nikitandro commented on packages/server/controllers/answer.ts
> +  const { answerId } = request.params;
Можем ли мы быть уверены, что `answerId` никогда не будет undefined

2023-11-16 12:10 UTC, nikitandro commented on packages/server/controllers/thread.ts
> +  }
Очень часто повторяется эта конструкция, возможно её можно вынести в отдельную функцию

2023-11-16 12:10 UTC, nikitandro commented on packages/server/middlewares/auth.ts
> +export const auth = async (request: RequestWithUser, _response: Response, next: NextFunction) => {
Название `auth` не очень информативное, мне кажется, лучше подойдёт `authMiddleware`

2023-11-16 12:10 UTC, nikitandro commented on packages/server/middlewares/validate.ts
> +export const validate = (request: RequestWithUser, response: Response, next: NextFunction) => {
Здесь тоже не очень информативное название функции, не очень понятно, что конкретно она валидирует, приходится догадываться исходя из контекста, читая тело функции.
Если я правильно понял её назначение, назвать её лучше `validateRequest`

2023-11-16 12:10 UTC, nikitandro commented on packages/server/models/Answer.ts
> +interface IAnswer {
Интерфейсы с префиксом `I` обычно означают интерфейс для класса, который должен реализовывать поля, которые задаёт этот интерфейс. Для моделей, на мой взгляд, логичнее использовать постфикс `Model`

2023-11-16 12:10 UTC, nikitandro commented on packages/server/types/RequestWithUser.ts
> +  user?: Record<string, any>;
Стоит типизировать user, или хотя бы использовать `unknown`, тип `any` стоит избегать

2023-11-16 12:10 UTC, nikitandro commented on packages/server/controllers/thread.ts
> +  }
Это относится и к остальным местам, где достаются параметры запроса

2023-11-16 12:11 UTC, Valeria2312 approved these changes

2023-11-16 12:15 UTC, brovan-rus commented on packages/server/middlewares/validate.ts
> +export const validate = (request: RequestWithUser, response: Response, next: NextFunction) => {
Смотри, эта мидлвара валидирует ошибки, которые пришли из либы валидации и отправляет их клиенту. Сама валидация в роуте, например
```
commentRoutes.post(
  '/',
  body(['text', 'answer']).escape().notEmpty().trim(),
  validate,
  createComment,
);
```

2023-11-16 12:18 UTC, brovan-rus commented on packages/server/controllers/answer.ts
> +  const { answerId } = request.params;
да, тут валидируем, что он не пустой 
```param(['answerId']).escape().notEmpty().trim(),```

2023-11-16 13:08 UTC, brovan-rus commented on packages/server/middlewares/auth.ts
> +export const auth = async (request: RequestWithUser, _response: Response, next: NextFunction) => {
Там, где используются миддлвары же будет понятно, что это миддлвара. Так, мы не пишем о типе в папке types о том, что это UserType, а просто называем его User

2023-11-16 13:09 UTC, brovan-rus commented on packages/server/middlewares/validate.ts
> +export const validate = (request: RequestWithUser, response: Response, next: NextFunction) => {
Аналогично как прошлом ответе

2023-11-16 13:20 UTC, brovan-rus commented on packages/server/controllers/thread.ts
> +  }
Тут проблема, что запрос, переданный в центральный обработчик ошибок не внутри миддлавы (если next передавать через аргумент), не останавливает цепочку запросов. И сервер падает. Хотел изначально кидать ошибку из самой функции checkAuthor

2023-11-16 13:24 UTC, nikitandro commented on packages/server/middlewares/auth.ts
> +export const auth = async (request: RequestWithUser, _response: Response, next: NextFunction) => {
Если он лежит в папке models, то имеет смысл назвать его `UserModel`. 
Мы ведь используем префиксы `I`, даже если знаем, что это интерфейс
Так же и здесь
Явное лучше неявного,

2023-11-16 13:39 UTC, merged