Feature/cod 15
Vladimir9812/middle.game.praktikum.yandex pull request #8
Opened 2023-09-18 13:17 UTC by kipish0293

Add component 404 (Page not found) with styles and icons

2023-09-18 19:29 UTC, brovan-rus requested changes

2023-09-18 19:29 UTC, brovan-rus commented on packages/client/src/pages/notFound/NotFoundPage.css
> +  margin-top: '-50px';
Отрицательный margin - плохая практика, обычно можно обойтись без него

2023-09-18 19:29 UTC, brovan-rus commented on packages/client/src/pages/notFound/NotFoundPage.css
> +    sans-serif;
Шрифт можно не указывать - он зашит в тему

2023-09-18 19:29 UTC, brovan-rus commented on packages/client/src/pages/notFound/NotFoundPage.tsx
> +  return (
Я вынес общий компонент Link, можно использовать его.

2023-09-18 19:29 UTC, brovan-rus commented on packages/client/src/pages/notFound/NotFoundPage.css
> +  line-height: 1em;
В Чакре размеры line-height в rem

2023-09-18 19:29 UTC, brovan-rus commented on packages/client/src/pages/notFound/NotFoundPage.tsx
> +          <Text className="not-found__title">
Для title используй heading c параметром as="h1", если это - заголовок первого уровня. Размеры и отступы можно почти все брать из базовой темы в чакре или модифицировать ее - таблица в доке тут
https://chakra-ui.com/docs/styled-system/theme

2023-09-18 19:45 UTC, kipish0293 commented on packages/client/src/pages/notFound/NotFoundPage.css
> +    sans-serif;
@brovan-rus в момент разработки моей задачи еще не был зашит, как по твоему лучше поступить? мне убрать его сейчас и ждать когда твои изменения заедут в дев?

2023-09-18 20:01 UTC, kipish0293 commented on packages/client/src/pages/notFound/NotFoundPage.css
> +  line-height: 1em;
@brovan-rus Поправил

2023-09-18 20:02 UTC, kipish0293 commented on packages/client/src/pages/notFound/NotFoundPage.css
> +  margin-top: '-50px';
@brovan-rus Убрал

2023-09-18 21:26 UTC, kipish0293 commented on packages/client/src/pages/notFound/NotFoundPage.tsx
> +  return (
@brovan-rus использовал

2023-09-18 21:26 UTC, kipish0293 commented on packages/client/src/pages/notFound/NotFoundPage.css
> +    sans-serif;
@brovan-rus убрал

2023-09-18 23:24 UTC, brovan-rus requested changes

2023-09-18 23:24 UTC, brovan-rus commented on packages/client/src/pages/notFound/NotFoundPage.css
> +    sans-serif;
Так, вроде, остался шрифт

2023-09-19 17:30 UTC, Vladimir9812 approved these changes

2023-09-19 17:31 UTC, merged