Feature/cod 27 Add ProfilePage
Vladimir9812/middle.game.praktikum.yandex pull request #9
Opened 2023-09-19 17:26 UTC by Valeria2312

2023-09-20 08:49 UTC, nikitandro commented on packages/client/src/pages/profile/Profile.tsx
> +// const data = {
Комментарии с моковыми данными лучше не оставлять

2023-09-20 08:53 UTC, nikitandro commented on packages/client/src/components/ProfileItem/ProfileItem.tsx
> +        // eslint-disable-next-line max-len
Здесь не очень понятно, зачем отключен max-len для строчки, вроде как есть возможность не выйти за разрешённый предел

2023-09-20 08:55 UTC, nikitandro commented on packages/client/src/pages/editProfile/editProfile.tsx
> +import { EditProfileForm } from '../../components/EditProfileForm/EditProfileForm';
Думаю, стоит использовать алиас путей @app/<dir-name>

2023-09-20 08:56 UTC, nikitandro commented on packages/client/src/pages/profile/Profile.tsx
> +import { EditIcon } from '../../components/icons/Edit';
Алиасы

2023-09-20 08:59 UTC, nikitandro requested changes
В основном, всё хорошо

2023-09-20 12:16 UTC, kipish0293 reviewed
В общем все хорошо, я бы убрал инлайн стили в css файлы и подумал на счет асинхронных reducers (extraReducers)

2023-09-20 12:16 UTC, kipish0293 commented on packages/client/src/components/EditProfileForm/EditProfileForm.tsx
> +              fontSize: '28px',
Мне кажется было бы читабельней, если бы стили были вынесены во вне

2023-09-20 12:16 UTC, kipish0293 commented on packages/client/src/components/ProfileItem/ProfileItem.tsx
> +        // eslint-disable-next-line max-len
Я в своей задаче на обработчик ошибок поставил правилу 150 символов, потому что 100 очень мало

2023-09-20 12:16 UTC, kipish0293 commented on packages/client/src/pages/main/Main.tsx
> +            <Link to="/edit-profile">Edit Profile Page</Link>
Мне кажется редактирование профиля должно быть по тому же роуту, что и профиль. И включался по внутреннему стейту

2023-09-20 12:16 UTC, kipish0293 commented on packages/client/src/pages/profile/Profile.tsx
> +              width: '307px',
Опять инлайн стили

2023-09-20 12:16 UTC, kipish0293 commented on packages/client/src/store/slices/ActionCreators.ts
> +    const response = await fetch('https://jsonplaceholder.typicode.com/users');
@Vladimir9812 @Valeria2312  Я думал асинхронные события мы выносим в extraResucers , пример есть в чате в телеге

2023-09-20 14:33 UTC, brovan-rus requested changes
Плюс необходимо добавить на страницу редактирование профиля навигацию (ту, что с иконками слева). Не увидел её.

2023-09-20 14:33 UTC, brovan-rus commented on packages/client/src/components/EditProfileForm/EditProfileForm.tsx
> +              fontSize: '28px',
+

2023-09-20 14:33 UTC, brovan-rus commented on packages/client/src/components/ProfileItem/ProfileItem.tsx
> +      w="508px"
Тут и везде дальше. Лучше использовать встроенные размеры chakra, даже, если они немного отходят от макета. Либо модифицировать тему. 
Посмотреть их можно тут https://chakra-ui.com/docs/styled-system/theme, перевести px в rem - тут https://nekocalc.com/px-to-rem-converter
То есть по таблице 508px = 31.75rem, по таблице -  lg: '32rem', то есть можно записать ``w="lg"``. Если нужны модификации или есть сомнения в базовом поведении - проверяем файл chakraTheme в корне клиента.

2023-09-20 14:33 UTC, brovan-rus commented on packages/client/src/components/ProfileItem/ProfileItem.tsx
> +      paddingBottom="9px"
То же самое, что в предыдущем комменте (и везде дальше) + сокращенные наименования chakra, их можно посмотреь тут https://chakra-ui.com/docs/styled-system/style-props
То есть можно записать pb="2.5" (округляем до 10px)

2023-09-20 14:33 UTC, brovan-rus commented on packages/client/src/components/ProfileItem/ProfileItem.tsx
> +      <span style={{ fontSize: '28px', letterSpacing: '5.6px' }}>{name}</span>
Здесь и везде дальше. Инлайновые стили применяем только, если меняем из из js напрямую. В других случаях стилизуем классами. 
Может быть тут логичнее использовать тэг чакры.

2023-09-20 14:33 UTC, brovan-rus commented on packages/client/src/pages/editProfile/editProfile.tsx
> +        backgroundColor="#CBFDFD"
Здесь и везде дальше. Не указываем напрямую цвета, все цвета определяем через тему.

2023-09-20 14:33 UTC, brovan-rus commented on packages/client/src/store/slices/ActionCreators.ts
> +// };
Код не должен идти в задачу, если он в ней не использеутя. Можно коммитить строчки частично. Если код на будущее - стоит добавить коммент TODO

2023-09-20 20:06 UTC, brovan-rus requested changes

2023-09-20 20:06 UTC, brovan-rus commented on packages/client/src/components/EditProfileForm/EditProfileForm.tsx
> +          <span
Тут необходимо использовать тэг Label или соответствующий аналог из chakra ui, чтобы связать label и input для acessability. Или прокинкуть его в FormInput

2023-09-20 20:06 UTC, brovan-rus commented on packages/client/src/components/EditProfileForm/EditProfileForm.tsx
> +    text: 'Name',
Более информативно назвать label

2023-09-20 20:06 UTC, brovan-rus commented on packages/client/src/store/slices/ActionCreators.ts
> +// const baseUrl = 'ya-praktikum.tech/api/v2';
Лишний коммент - в итоговый код лучше не писать пустые комменты, либо помечать из //TODO

2023-09-20 20:06 UTC, brovan-rus commented on packages/client/src/store/slices/ActionCreators.ts
> +    // заменить адрес
TODO

2023-09-20 20:15 UTC, brovan-rus commented
Еще по наименованию коммитов - стоит из делать информативными и атомарными, в данном ПР

- Два коммита с одинаковым названием
- Один из них на русском
- "add profile and editProfile" - если есть and, то это указывает на то, что коммит можно было разделить на 2.

2023-09-21 20:52 UTC, Vladimir9812 commented on packages/client/src/store/slices/ActionCreators.ts
> +    const response = await fetch('https://jsonplaceholder.typicode.com/users');
Да, так и есть. Необходимо это реализовать через createAsyncThunk

2023-09-22 16:35 UTC, brovan-rus requested changes

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/components/EditProfileForm/EditProfileForm.tsx
> +    name: 'oldPassword',
Наименование name для консистентности лучше именовать с нижним подчёркванием типа password_old.

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/components/EditProfileForm/EditProfileForm.tsx
> +    console.log(passwordData);
Если у тебя уже реализована логика сабмита, то нужно удалить косоль лог. Тут и дальше

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/components/FormButton/FormButton.tsx
> +    <Button size="lg" colorScheme="red" onClick={onClick}>
Сабмит формы должен происходить по событию onSubmit на форме.

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/components/FormInput/FormInput.tsx
> +        // width="lg"
Лишний коммент

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/components/ViewProfileContent/ViewProfileContent.tsx
> +  const profileItems = user ? (
По сути у нас не может не быть юзера, так как мы будем закрывать доступ ко всем страницам для неавторизованных пользователей, кроме логина и пароля.

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/components/ViewProfileContent/ViewProfileContent.tsx
> +        backgroundColor="#CBFDFD"
Цвета не указываем напрямую, только через свойства темы

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/components/ViewProfileContent/ViewProfileContent.tsx
> +        h="47rem"
Тоже, если есть возможность, лучше подобрать +- размеры из чакры. Например "3xl" = 48rem

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/components/ViewProfileContent/ViewProfileContent.tsx
> +        <Flex flexDirection="column" style={{ paddingTop: '1.6rem' }}>
Не указываем инлайновые стили. Только, когда меняем их из кода. В остальных случаях либо классы, либо свойства элементов чакры

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/components/ViewProfileContent/ViewProfileContent.tsx
> +  const profileItems = user ? (
Ещё момент, можно inputs переименовать в fields, в них указать все поля. Потом из них фильровать - profile fields. В случае формы мапить из них инпуты, в слуаче профиля - ProfileIntem. По сути name - это тот же label. Тогда, если мы решим поменять название одного из полей, нам нужно будет только в одном месте его изменить.

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/components/ViewProfileContent/ViewProfileContent.tsx
> +            style={{ width: '100%', height: '100%' }}
инлайновые стили, компонент должен быть из чакры, а не img

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/pages/profile/Profile.tsx
> +  return user ? (
Если нет юзера, то страница будет недоступна. Проверку можно не делать

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/store/slices/UserActionCreators.ts
> +  const response = await fetch(`${baseUrl}/auth/signin`, {
Работу с запросами лучше вынести в отдельный класс API, как обертка над fetch.

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/store/slices/UserActionCreators.ts
> +  return response.json();
Здесь и везде добавить обработку ошибок fetch.

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/store/slices/UserActionCreators.ts
> +      'Content-Type': 'application/json;charset=utf-8',
Тут и дальше, заголовки можно вынести в переменную.

2023-09-22 16:35 UTC, brovan-rus commented on packages/client/src/store/slices/UserSlice.ts
> +  // user: null, ошибка lint
Напиши undefined. Тут опание - обоснование правила https://github.com/sindresorhus/meta/discussions/7

2023-09-23 15:20 UTC, brovan-rus approved these changes

2023-09-24 09:25 UTC, Brarion approved these changes
Хорошая работа :)
Немного смущает только строка `if (response.status !== 200) {`, потому что вдруг прилетит 2xx, но не 200, тогда у вас будет ошибка, но с другой стороны, судя по классу `MyApi` вряд ли такое случится (опять же судя по внутренним методам)

2023-09-24 09:46 UTC, Vladimir9812 requested changes

2023-09-24 09:46 UTC, Vladimir9812 commented on packages/client/src/components/EditProfileContent/EditProfileContent.tsx
> +}) {
Тип пропсов необходимо вынести в отдельный тип Properties над компонентом как в других компонентах приложения. (Не только в этом компоненте эта проблема)

2023-09-24 09:46 UTC, Vladimir9812 commented on packages/client/src/components/EditProfileForm/EditProfileForm.tsx
> +}) {
Вот тут пропсы

2023-09-24 09:46 UTC, Vladimir9812 commented on packages/client/src/components/FormInput/FormInput.tsx
>  type FormInputProperties = {
Просто Properties (по аналогии с другими компонентами)

2023-09-24 09:46 UTC, Vladimir9812 commented on packages/client/src/components/ViewProfileContent/ViewProfileContent.tsx
> +  fields: TField[];
В отдельный тип

2023-09-24 09:46 UTC, Vladimir9812 commented on packages/client/src/pages/profile/Profile.tsx
> +
Необходимо добавить алиас для этого. Пример есть на главной странице с counter

2023-09-24 09:46 UTC, Vladimir9812 commented on packages/client/src/pages/profile/Profile.tsx
> +  }, []);
Можно попробовать реализовать это внутри async Thunk

2023-09-24 09:46 UTC, Vladimir9812 commented on packages/client/src/store/slices/requestUser.ts
> +const baseUrl = 'https://ya-praktikum.tech/api/v2';
Этот файл должен не в slices храниться, а в папке api

2023-09-27 14:12 UTC, merged